# Generated by Django 5.0.1 on 2024-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Podcast',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
