# Generated by Django 5.0.4 on 2024-04-17 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_podcastimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastimage',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_imgs', to='api.podcast'),
        ),
    ]
