# Generated by Django 5.0.4 on 2024-04-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_podcastimage_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='mobile',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='seller/imgs/'),
        ),
    ]
