# Generated by Django 5.0.4 on 2024-05-01 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_creator_mobile_creator_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('reviews', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_customers', to='api.customer')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.podcast')),
            ],
        ),
    ]
