# Generated by Django 5.0.4 on 2024-05-01 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_customeraddress_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customeraddress',
            table=None,
        ),
    ]
