# Generated by Django 5.0.3 on 2024-05-22 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_creator_id_podcastrating'),
        ('api', '0013_alter_customeraddress_table'),
    ]

    operations = [
    ]
